use std::{hint::black_box, str::FromStr as _};

use criterion::{criterion_group, criterion_main, BatchSize, Criterion};
use slidy::algorithm::algorithm::Algorithm;

fn bench_from_str(c: &mut Criterion) {
    c.bench_function("algorithm/from_str", |b| {
        b.iter(|| {
            black_box(Algorithm::from_str(
                "DR2D2LULURUR2DL2DRU2RD2LDRULULDRDL2URDLU3RDLUR3DLDLU2RD3LU3R2DLD2LULU2R3D3",
            ))
        });
    });
}

fn bench_simplified(c: &mut Criterion) {
    let algorithm_str = "DL2URDURDRULDLR3UDR2RL4LLUUURDDUURR4URLULLRRDDLLRLU2UDUURURRL4RLLDL3DD3ULD\
    D2LRRRRLR5RRLUDDUR2DDLUUDRDRRDRL2L29RDLURD2RLURL4RURLDRRLLRURR2DRLUUDLURRRUDRLUUDLD2URLRRRDULLRRDULLU\
    2DD2UDUDLD6U9LDD2RU2DLR3U2R3U3RUULUURRD7URDLUL2DUDURL2LUR2LURRURLDUUUUDUUR4RDLLULRUDRUUDRLLDDLLURDUDU\
    LL3RLR9UUDDDULLRDLU2LUDUDURL5LDDLRLLLDUUDR3DRD2UL3UL2DDU2RDDUDDDRLU3RLUL2DUU3RUL2LRLD2LLRLRRRR3UUD3RR\
    LD2D4RURRDRRURLUDDLDL2DDURLDDUUDRRR2L2DLLUD3DR4URD2DRDU8RULUUDRURRDLDLULDLDRLR3DUDRRL2UDDULURLR11LDRU\
    D2RD5DLD2DDLRUUDRDLDLD9UDLUDDR3UDLLRULULU2LLRUD2R11D2U11DDUUUDURR2LDUULRRDRL2RRDUDLDLLLUDRD14DD3DRLL3\
    U25R2L2LULDLDL2RULDRD2LRDLRLLRR2DRULU4UURLDRDLUUDRDDUR3RUULLUL2U5UDRULRLUULULURRUD2RDRDDRU4RU2ULDDDUR\
    UUUDUUUDUUDD2LDLDUDURLULRRLU6DL2LRLD2L2L2RLDR2RUR2RL2ULLL2DULRDU3LDLUD2RUUUULUDD2LL2LRDDUDLDULRDDLLUD\
    D2URL2RURURRLUR2RDURD4R3DDDD4ULUD2URUDUDDRLDUDD2DRDULLDLRDUUU2RR2UL2RUUDULULDURRUD2ULDUD2DDURURLRL4RU\
    DRLRURRR3UUUL45UL2U2RRUL2RDD4RLLR2UUUDDLLLRUUDL2UDRLLDDRRRRL2UURDLRRLLRLDDLLLLRDLD2DD2RRURR2U2DLRL2LL\
    DLLU2D3ULUDDLDUULD3LUU6RLUDUUDLDDDLDRD4RDLUDDRDL2D2LDLD2RUR2RRURULUR3RRURDL2UD2LRDD2LURL3LLU6LLR4LUUL\
    ULDULLUULLLLRL6LLURLLLULLR3RURU2DDRURL2D2RDRRRD2D3LLDR5DRULLDUULRD2DRLLULLDU2R2LR2";

    c.bench_function("algorithm/simplified", |b| {
        b.iter_batched(
            || Algorithm::from_str(algorithm_str).unwrap(),
            |a| black_box(a.simplified()),
            BatchSize::SmallInput,
        );
    });
}

criterion_group!(algorithm, bench_from_str, bench_simplified);
criterion_main!(algorithm);
